#!/bin/bash
# Create a script that creates the directories welcome/, welcome/to/ and welcome/to/school in the current directory.You are only allowed to use two spaces (and lines) in your script, not more.
mkdir -p welcome/to/school
