#!/usr/bin/env bash
# This script displays:
# -To infinity and behond indefinitely
# -With a sleep 2 in between each iteration
# -I am invincible!!! whan receiving a SIGTERM signal
trap "echo 'I am invincible!!'" SIGTERM
while :; do e cho 'To infinity and beyond'; sleep 2; done
